<p>
<a href="<?=$this->url(array("action"=>"create"))?>"><?=$this->translate("Add new menu")?></a>
</p>
<table>
<thead>
<tr>
<th></th>
<th>Name</th>
<th>Access level</th>
<th colspan="3"></th>
</tr>
</thead>
<?=$this->partialLoop("partials/menu-partial.phtml",$this->menus);?>
</table>
<? $this->headScript()->appendFile($this->baseUrl("/js/jQuery.js"))?>
<?=$this->inlineScript()->appendFile($this->baseUrl("/js/delete.js")) ?>