<?
// @ZEND utiliser , afficher Zend_Db_Profiler
// @ZEND get default db adapter
$db = Zend_Db_Table::getDefaultAdapter();
$profiler = $db->getProfiler();
if($profiler->getEnabled() && $profiler->getTotalNumQueries()>0):
?>
<h2>Database Profiling Report</h2>
<p>
Total queries executed : <?=$profiler->getTotalNumQueries()?>.
</p>
<p>
Total elapsed time : <?=$profiler->getTotalElapsedSecs()?>.
</p>
<table>
<thead>
<tr>
	<th>#</th>
	<th>Query</th>
	<th>Time</th>
</tr>
</thead>
<tbody>
<?
  foreach($profiler->getQueryProfiles() as $queryNumber=>$query):
?>
<tr>
<td><?=$queryNumber+1?></td>
<td><?=$query->getQuery()?></td>
<td><?=$query->getElapsedSecs()?></td>
</tr>
<?
endforeach;
?>
</tbody>
</table>
<?  
endif;

