<div id="view-content">
    <h2>Introduction</h2>
    <p>DSnippet helps developpers to save code snippets, share them and
    search in a codebase by providing a web application usable in any browser.
    With DSnippet developpers no longer need to search the net or their computer
    for a specific code, they can save a snippet on the website , as a reminder of how
    they solve an issue or a code of interest.
    DSnippet uses client side technologies like jQuery , Backbone , Underscore , RequireJS and Prettify.js
    </p>
    <h2>Registration process</h2>
    <p>You can search public snippets without registering.
    to save , edit , and favorite other people snippets , go to the registration page , fill the form 
    and a confirmation mail will be sent before you can actually use your account.
    </p>
    <h2>Snippet edition</h2>
    <p>You can save snippets in various langages , update and delete them
    make it public or private , or favorite other people snippets.
    </p>
    <h2>Snippet search</h2>
    <p>In the current application version , suggestions based on the snippet title are being made as you type in the
    the search box. Selecting one suggestion will display the selected title.
    Pressing search will list every snippets that fits the search input.
    </p>
    <h2>Snippet definition guidelines</h2>
    <ul>
      <li>Add a descriptive title that explains what the snippet is about.
      If in a language , a snippet uses a framework or a library , prefix the title with :
      LIBRARY - FRAMEWORK - snippet title
      </li>
      <li>Add a short description, like a sentence explaining what problem the snippet resolves</li>
      <li>Avoid citations , copying other people's code. If you do , provide the source url as a comment at the top of the snippet and ask for permissions. </li>
    </ul>
</div>
